### ISSUE TITLE
v1 sous MacOS, impossible de créer une fiche

### ISSUE THREAD

**Issue by ljegou** [graphlab-fr/cosma#1]
Après installation et autorisation d'ouverture (sécurité), je ne peux pas créer de fiche.
- la liste déroulante des types est vide
- au clic sur "Ok", message d'erreur.

Voici des captures :
<img width="533" alt="Capture d’écran 2021-09-10 à 09 16 14" src="https://user-images.githubusercontent.com/5158753/132815245-7060d6d6-7db8-4cb7-9d88-61484b562ef0.png">
<img width="333" alt="Capture d’écran 2021-09-10 à 09 16 26" src="https://user-images.githubusercontent.com/5158753/132815251-980be585-47bd-4370-86ff-b09cf9d063cf.png">

**Comment by oledeuff** [comment]
Bonjour

Deux hypothèses. La première est liée à un problème de statut
d'administrateur machine sous mac.
La seconde est liée au fait qu'il vous faut avoir rempli les préférences
d'abord et notifier un répertoire dans lequel vont se trouver vos fiches.

Prévenez-vous de l'évolution du problème

bonne journée
Olivier Le Deuff.
Maître de conférences en SIC. Habilité à diriger des recherches
Laboratoire Mica. Université de Bordeaux Montaigne
Montaigne de Bordeaux.
 0687653127.

**Comment by ljegou** [comment]
Merci pour votre réponse, en effet, après la définition d'un répertoire par défaut inscriptible, je peux créer des fiches.
