### ISSUE TITLE
Compatibility with Markdown links

### ISSUE THREAD

**Issue by PhilB-RLB** [graphlab-fr/cosma#109]
### Which part of Cosma is your request about?

- [X] command-line interface
- [ ] cosmoscope (HTML file)
- [ ] documentation
- [ ] other

### Describe your request:

Hello there,
thank you for this wonderful piece of software.

Nevertheless, I wonder if it world be complicated to analyze standard markdown links :
[My Link](/path_to_my_file/my_file.md)
instead of the Wikilink :
[[My Link]

I ask for this because I use Hugo to produce my Knowledge Management Site and Hugo is not compatible with the Wikilink syntax.

Another question : would it be possible with the cosmoscope to obtain a "local" graph representation instead of the whole one ?

Phil.B

**Comment by infologie** [comment]
@PhilB-RLB Thanks for opening an issue!

Your suggestion matches another one: Support for "\[text\]\(file.md\)" link syntax https://github.com/graphlab-fr/cosma/issues/42 Feel free to track it so you're notified if we move on it.

Regarding your question:

- In the cosmoscope, you can filter the display dynamically by using Focus on a node (bottom left of the graph), by hiding types, by selecting keywords.
- Before running `cosma modelize`, you can [Exclude records from the cosmoscope](https://cosma.arthurperret.fr/user-manual.html#excluding-records-from-the-cosmoscope) by using the `record_filters` parameter in the configuration. This feature is going to be improved in the next development cycle, which is about to start.

**Comment by PhilB-RLB** [comment]
Oh, I didn't noticed that this subject was already mentioned. I will check this ticket.

For the "local" graph, yes I've seen that I can filter the display dynamically but I was more asking for a sort of html syntax (produced by my Hugo site) in order to automatically print the graph...

**Comment by infologie** [comment]
> For the "local" graph, yes I've seen that I can filter the display dynamically but I was more asking for a sort of html syntax (produced by my Hugo site) in order to automatically print the graph...

I'm sorry, I don't understand. Could you be more specific?

**Comment by PhilB-RLB** [comment]
Sorry for my poor english (I'm french guy) ...

Actually I would like to embed a "local" cosmoscope graph into my Hugo site. For example a page which describe the author 'Victor Hugo' should display a graph with only the other page with link to this author.

**Comment by PhilB-RLB** [comment]
I forgot to mention that I use the Amethyst Hugo theme which you can see in action here : https://amethyst.bencuan.me/.
On this home page you will see the global graph of this site (at the bottom).

Now if you go to https://amethyst.bencuan.me/setup/config/ you will see what I call a "local" graph which show only the "pages" in relation.

**Comment by infologie** [comment]
Ok, with this example I get it! (Thanks for making the effort to write in English so non-French speaking people can read our discussion.) You're asking if there is a way to integrate Cosma with a CMS such as Hugo, in order to reproduce the graph view functionality of Amethyst, but with the option to restrict the graph to a "local" view, like in Cosma's Focus. Cosma doesn't have an API, so I don't see a way to do this conveniently on a large scale. It would be much simpler to open an issue about this on the Amethyst GitHub repository.

**Comment by PhilB-RLB** [comment]
Ok, thank you for your answer.
