### ISSUE TITLE
[Bug] Message in french

### ISSUE THREAD

**Issue by IgnacioHeredia** [graphlab-fr/cosma#116]
### What version of Cosma are you using?

2.4.0

### On which operating system(s) did you observe the bug?

- [ ] macOS
- [ ] Windows
- [X] Linux

### What version of the operating system are you on?

Ubuntu 20.04

### Actions leading to the bug

There a message in French that shows in the right panel when you open the graph but haven't yet selected a node. I understand French but it's nevertheless weird to have a French message while the rest of the UI is in English. ;)

`Cliquez sur un nœud du graphe ou dans un élément de l'index pour ouvrir une fiche.`

![image](https://github.com/graphlab-fr/cosma/assets/16413205/74b9d4ea-4ed6-49db-84fd-2ac890e8177e)

Thanks!

### Bug description

Described above.

**Comment by infologie** [comment]
@IgnacioHeredia Thanks for reporting this! It should be easy to fix.

**Comment by infologie** [comment]
Fixed in [v2.4.1](https://github.com/graphlab-fr/cosma/releases/tag/2.4.1).
