### ISSUE TITLE
Dead link (to the cli vesion [Bug] 

### ISSUE THREAD

**Issue by QWxleA** [graphlab-fr/cosma#17]
### Actions leading to the bug

Under Downloads is the line: `On Linux? Download [the command line version](https://cosma.graphlab.fr/en/docs/manuel-utilisation/#cosma-cli)`

That link is a 404, missing link

### Bug description

link should exsit

### What is your operating system?

- [X] Windows
- [ ] macOS

### What version of the operating system are you on?

Actally on Linux

### Additional information

Impossible to write a bug-report from Linux too?!?

**Comment by infologie** [comment]
That's not the way I wanted to welcome Linux users… Thanks for taking the time to report it. Fixed the link, and updated the bug report template as well.
