### ISSUE TITLE
Erreur dans la création d'une nouvelle fiche

### ISSUE THREAD

**Issue by LaBretelle** [graphlab-fr/cosma#2]
Bonjour,

Sur Windows 10 64 bits, il m'est impossible de créer une fiche, j'obtiens le message "Erreur inconnue". Ce message apparaît lorsque le répertoire des fiches choisi est le répertoire de Cosma, j'ai l'impression.

 Lorsque j'ai réinstallé Cosma en supprimant \appData\Roaming\cosma et en choisissant un autre répertoire de fiches, cela fonctionne.

Merci !

**Comment by oledeuff** [comment]
Bonjour

Merci pour votre retour.
Effectivement, il faut renseigner un répertoire dans les préférences pour
pouvoir créer une fiche.
On prend note de vos observations en tout cas en matière de bug.

Merci et bonne journée
Olivier Le Deuff.
Maître de conférences en SIC. Habilité à diriger des recherches
Laboratoire Mica. Université de Bordeaux Montaigne
Montaigne de Bordeaux.
 0687653127.
