### ISSUE TITLE
[Enhancement] Release Cosma Demo in English language

### ISSUE THREAD

**Issue by menelic** [graphlab-fr/cosma#20]
### Which part of Cosma is your request about?

- [ ] GUI version (Electron-based app)
- [ ] CLI version (command-line tool)
- [ ] cosmograph (records & cosmoscope creation)
- [ ] cosmoscope (exported graph & records)
- [X] documentation
- [ ] other

### Describe your request:

This is a great project and deserves more visibility - I believe an English version of the interactive live demo (which I believe is just an export html created by the app) could help. Seeing that English versions of the texts in the demo exist as parts of the English documentation, this seems to be an easy thing to do given the cosma html output. 

Apologies if there is a language switch in the demo - I did not find it and searching for terms from the English documentation did not yield any results. The English FAQ links to the French demo.

**Comment by infologie** [comment]
> This is a great project and deserves more visibility

Thank you!

It's a good thing you opened a ticket, I had forgotten about the demo. It's now available in English: https://cosma.graphlab.fr/en/demo.html The homepage and FAQ should correctly link to it. I made some screenshots in English for the homepage as well while I was at it.
