### ISSUE TITLE
[Bug] Cosma does not open any more a new tag in the browser

### ISSUE THREAD

**Issue by damienbelveze** [graphlab-fr/cosma#24]
### Actions leading to the bug

Hi, 
Thank you for having developed this app!
I have tried it with some success at the beginning of this month, but now anytime I try to use it (by clicking on the Cosma.exe file), nothing happens (no matter which browser I am using, Firefox or Chrome). But If I try to delete cosma files, a message is prompted stating that Cosma is being used. 
I have tested the 7th of June version and still face the same issue. 
Could you please help me?

Regards, 

Damien Belvèze

### Bug description

Clicking on Cosma.exe file won't make a new tab open in my browser with the Cosma dashboard

### What is your operating system?

- [ ] macOS
- [X] Windows
- [ ] Linux

### What version of the operating system are you on?

Windows10

**Comment by infologie** [comment]
Bonjour Damien (je passe au français, ce sera plus simple). Je ne suis pas sûr de comprendre quel est le bug. Ouvrir Cosma.exe n’ouvre pas de navigateur mais l’application Cosma, dans laquelle s’affiche le cosmoscope. Depuis cette application, tu peux éventuellement cliquer sur un lien hypertexte qui serait présent dans une fiche, ce qui ouvre la page correspondante dans ton navigateur par défaut. Et tu peux également exporter un fichier cosmoscope.html que tu peux ouvrir dans ton navigateur. Mais ce sont les deux seuls cas possibles où Cosma a un lien avec ton navigateur.

Maintenant, si le problème est que tu ouvres Cosma.exe et que ça affiche une fenêtre vide, alors c’est probablement un bug lié au changement entre deux versions de Cosma. Je te conseille de suivre la procédure détaillée [ici dans la doc](https://cosma.graphlab.fr/docs/manuel-utilisation/#mises-a-jour) en téléchargeant bien la version 1.1 (pas la 1.0 ni la 1.2 qui a été brièvement mise en ligne hier). Tu télécharges automatiquement la 1.1 si tu passes par le site : https://cosma.graphlab.fr/telecharger/.

**Comment by damienbelveze** [comment]
Bonjour @infologie . En effet, je ne me souvenais plus que Cosma n'ouvrait pas une page du navigateur mais une page dans laquelle s'affiche le cosmoscope. Merci d'avoir attiré mon attention sur le fichier config.json à supprimer dans les ...\Appdata\Roaming\Cosma. Après l'avoir supprimé, j'ai relancé Cosma et ça fonctionnait à nouveau. En cas de besoin, je referai la manoeuvre lors des prochaines mises à jour. Merci beaucoup !
