### ISSUE TITLE
[Bug] Using @ without prompting a citation

### ISSUE THREAD

**Issue by kaizokuroo** [graphlab-fr/cosma#26]
### Actions leading to the bug

Hello graphlab team,

I am using cosma to create a big mindmap about (Syntactic) Universal Dependencies and some of the dependency names contain an @ as in `comp:aux@pass`, `subj@expl`, `comp:obl@agent`. When I generate the cosmoscope, I get the following error message: 

```
Les clés de citations suivantes n'ont pas été trouvées dans les données bibliographiques :

'pass' depuis comp_aux.md
'tense' depuis comp_aux.md
'pass' depuis comp.md
'tense' depuis comp.md
'x' depuis comp.md
'agent' depuis comp.md
'x' depuis comp.md
'expl' depuis comp.md
'relcl' depuis Groupe verbal relatif.md
'relcl' depuis mod.md
'x' depuis mod.md
'pass' depuis Passif.md
'pass' depuis Passif.md
'agent' depuis Passif.md
'expl' depuis Pronom personnel.md
'expl' depuis Pronom reflechi.md
'relcl' depuis Pronom relatif.md
'pass' depuis subj.md
'expl' depuis subj.md
```

The cosmoscope works fine and I have no real problem, but the error message shows that cosma seems to detect any `@` as a citation. I tried esacping the character with `\@` and such but nothing worked. It is not a serious issue but I thought it might be worth mentioning.

### Bug description

I have nothing to add here, the @ cannot simply be used without prompting a citation.

### What version of Cosma are you using?

{"label"=>"CLI 1.1"}

### What is your operating system?

- [ ] macOS
- [ ] Windows
- [X] Linux

### What version of the operating system are you on?

Arch Linux

**Comment by infologie** [comment]
Thanks @kaizokuroo. Tagging @Myllaume, we’ll look into it.

**Comment by infologie** [comment]
@kaizokuroo So we looked into it, and it has to do with Zettlr's [Citr library](https://github.com/zettlr/citr), which Cosma uses to process citations. There's nothing we can do about it for now, so I'll leave the issue open. But since it only generates false warnings in the log, the impact on usability is limited.
