### ISSUE TITLE
[Bug] Le lien pour télécharger la version macOS ne marche pas

### ISSUE THREAD

**Issue by huyz** [graphlab-fr/cosma#28]
### Actions leading to the bug

- Aller a https://cosma.graphlab.fr/en/
- Cliquer sur `Download (macOS)`

### Bug description

`Not Found`

### What version of Cosma are you using?

{"label"=>"GUI 1.2"}

### What is your operating system?

- [X] macOS
- [ ] Windows
- [ ] Linux

### What version of the operating system are you on?

macOS 12.5 (Monterey) Apple M1 Max (ARM) 

### Additional information

C'est quoi la dernière version? 1.1 ou 1.2?  Le [repo sur Github](https://github.com/graphlab-fr/cosma/) dit un peu les deux.

**Comment by infologie** [comment]
Merci @huyz ! La dernière version est la 1.1. La 1.2 a été repoussée. Je n'avais pas mis à jour le site, qui renvoyait vers une 1.2 qui n'existe pas. C'est réglé maintenant.
