### ISSUE TITLE
[Enhancement] Support for other metadata syntax?

### ISSUE THREAD

**Issue by bambirombi** [graphlab-fr/cosma#29]
### Which part of Cosma is your request about?

- [ ] GUI version (Electron-based app)
- [ ] CLI version (command-line tool)
- [ ] cosmograph (records & cosmoscope creation)
- [ ] cosmoscope (exported graph & records)
- [ ] documentation
- [X] other

### Describe your request:

I would like to know if you could support other syntax for the metadata. 

For example, I am using logseq and the properties (=metadata) syntax is this:
`type:: article` In zettlr it is: `type: article`
[Logseq-Properties](https://docs.logseq.com/#/page/term%2Fproperties?anchor=ls-block-60a78c12-4e12-4d81-a33f-9f63695aaf32)

I ask this because I saw that you use cosma with zettlr [Arthur](https://www.arthurperret.fr/blog/2021-10-20-zettlr-2.html), and I am afraid that the syntax of logseq won't work. 

I do not know if it currently works because I am a linux user and my terminal abilities are pretty limited. So let me know. And congratulations for this amazing piece of software! In logseq there is already a plugin to improve the default graph [logseq-graph-analysis](https://github.com/trashhalo/logseq-graph-analysis), but cosma looks even better.
And also continue publishing in your website, I enjoyed reading it.

**Comment by infologie** [comment]
@bambirombi I cannot say yes or no right away. I think making Cosma interoperable with Logseq would require more than just supporting its metadata format. I admit I don't know much about Logseq, I have just taken a quick look at the docs. But I can see that it's an outliner, that it uses titles as anchors for links, and that it supports bibliographic data in a way that is not Pandoc Markdown citations. So for Cosma to parse any of Logseq's format, we would need to work quite a bit. I would have to take a closer look at the use cases to determine if it's really worth it. Cosma remains tied to Pandoc's ecosystem and academic writing, hence the strong affinity with Zettlr and other tools that use a similar format, such as the Foam extension for VS Code.

I will leave this issue open. Next fall, when I'm free from dissertation writing, I will check Logseq’s documentation further, discuss this with @Myllaume and get back to you. I have read good things about Logseq as a free software alternative to Roam, so it at least deserves a closer look.

In any case, thank you very much for the kind words about our work!

**Comment by infologie** [comment]
@bambirombi I checked Logseq's documentation. Logseq's design principles are very different from what we are doing here, so we won't explore this issue further for now.
