### ISSUE TITLE
add 'keywords' as synonym of 'tags'

### ISSUE THREAD

**Issue by boutil** [graphlab-fr/cosma#3]
Hi,

I would like to know if you could add 'keywords' as a synonym for 'tags', as in Zettlr (see <https://docs.zettlr.com/en/core/yaml-frontmatter/#keywords-tags>). Indeed, pandoc recognizes 'keywords'. It would be useful if we could use the same YAML headers for notes and export them with pandoc, and at the same time explore them with Cosma.

Thank you for this great project! Merci

**Comment by oledeuff** [comment]
Thanks for your suggestion.
We will discuss about it for the next relase

Merci
Olivier Le Deuff.
Maître de conférences en SIC. Habilité à diriger des recherches
Laboratoire Mica. Université de Bordeaux Montaigne
Montaigne de Bordeaux.
 0687653127.

**Comment by infologie** [comment]
@boutil We added this in the [1.1 update](https://github.com/graphlab-fr/cosma/releases/tag/1.1). Thanks again for suggesting this!
