### ISSUE TITLE
[Enhancement] import .md files with "." in the filename

### ISSUE THREAD

**Issue by mcaruel** [graphlab-fr/cosma#30]
### Which part of Cosma is your request about?

- [ ] GUI version (Electron-based app)
- [ ] CLI version (command-line tool)
- [X] cosmograph (records & cosmoscope creation)
- [ ] cosmoscope (exported graph & records)
- [ ] documentation
- [ ] other

### Describe your request:

The filenames of my markdown notes contains intermediate `dots` before the final extension `.md`. For instance  I can have a filename like this : `references.book.kipling.junglebook.md`.
Is is possible to slightly modify the way cosma inspect the md notes folder so that such files are included ?
If you tell me where to look, I can try to do it myself.
Matthieu

**Comment by Myllaume** [comment]
Thanks for your feedback. I'll add this quickly.

**Comment by mcaruel** [comment]
Thank you Guillaume. I have other ideas too !

**Comment by mcaruel** [comment]
I just realise something. In fact Cosma Can import files with filenames that include `.`, so this request is in fact irrelevant. However to be visible in cosma the **id of the file** should contains only numbers. Mine contained numbers and letters...
It would be nice to allow any kind of string (maybe excluding some special characters).
