### ISSUE TITLE
[Bug] Problem generating a cosmocope with citations

### ISSUE THREAD

**Issue by vclzl** [graphlab-fr/cosma#35]
### Actions leading to the bug

Creating a cosmoscope without citations works perfectly. 
The three compulsory files are charged (json, csl and xml with French translations).
File > new cosmoscope with citations makes appear a bug report. 

### Bug description

<img width="902" alt="Capture d’écran 2023-02-26 à 19 18 18" src="https://user-images.githubusercontent.com/79601904/221429097-4d52962c-9e27-4ce1-9182-2ad1aa9e3e43.png">
<img width="899" alt="Capture d’écran 2023-02-26 à 19 18 07" src="https://user-images.githubusercontent.com/79601904/221429100-5d241be5-2b3c-4359-a690-dde0d6f967a8.png">

### What version of Cosma are you using?

GUI 1.1

### What is your operating system?

- [X] macOS
- [ ] Windows
- [ ] Linux

### What version of the operating system are you on?

Monterrey 12.6.3

**Comment by infologie** [comment]
Thank you for the feedback. We are planning important changes to Cosma, which includes suspending our work on the GUI. It will remain available via GitHub but we do not plan to provide any support or updates for it. We are going to reorganize our GitHub repos in the coming weeks to reflect this.

More info here: <https://cosma.graphlab.fr/en/roadmap/>

Getting started with the CLI: <https://cosma.arthurperret.fr/getting-started.html>
