### ISSUE TITLE
[Enhancement] Center graph on node after search

### ISSUE THREAD

**Issue by IgnacioHeredia** [graphlab-fr/cosma#39]
### Which part of Cosma is your request about?

- [ ] GUI version (Electron-based app)
- [ ] CLI version (command-line tool)
- [ ] cosmograph (records & cosmoscope creation)
- [X] cosmoscope (exported graph & records)
- [ ] documentation
- [ ] other

### Describe your request:

Hi,

just another possible improvement for the future.

After doing a search in the _Search tab_, when you select the record, the graph is not updated. I still lies in the same position. It would be nice to center the graph on the selected record.

As you can see the focused record is not show in the screen:

![Screenshot from 2023-05-16 00-00-24](https://github.com/graphlab-fr/cosma/assets/16413205/bf583094-efe4-4027-a8b3-8c4e1fcde42c)

Thanks!

Ignacio

**Comment by infologie** [comment]
Thanks @IgnacioHeredia for the feedback. This is one of our goals for the next update (two issues, two things that are on the top of our roadmap: you're psychic!). We're supposed to have a feature to center+zoom on a node when pressing C. I think it broke when we made changes to the graph (see #38). The idea is to have it work again and have the same effect automatically on some actions, including selecting a node from a search result. We'll keep you posted here.

**Comment by infologie** [comment]
@IgnacioHeredia We've made this enhancement in [v2.4](https://github.com/graphlab-fr/cosma/releases/tag/2.4.0). Happy testing!
