### ISSUE TITLE
[Bug] `chronological_record_meta` in `config.yml` can not be specified another custom meta.

### ISSUE THREAD

**Issue by uuanqin** [graphlab-fr/cosma#56]
### What version of Cosma are you using?

CLI 2.0.0

### On which operating system(s) did you observe the bug?

- [ ] macOS
- [X] Windows
- [ ] Linux

### What version of the operating system are you on?

Windows 10

### Actions leading to the bug

1. install cosma `npm install @graphlab-fr/cosma -g` , version 2.0.2
2. `cosma c` add a configure file and write it
3. run `cosma m`
4. open `cosmoscope.html` in Browser
5. click **Mode chronologique**

### Bug description

Since migration, all my markdown files have the same creation date on Windows. Fortunately, their front-matter has a `date` metadate field that records the actural creation date of the file. Its format is like _2023-07-10 23:16:32_.
I refered the user manual, which states that `chronological_record_meta` in cosma configuration file can be set to another metadata field declared in record_metas. 
Here is an example YAML configuration:
```yaml
chronological_record_meta: date
record_metas:
  - date
```
However, it didn't work as expected. After running `cosma m`, the `chronological_record_meta` reverted back to the default value 'created' . 

I questioned whether the format of `date` was incorrect, but I have tried _2023-07-10_, _20230710231632_ and _1650257016_(timestamp), none of which worked. Did I make any mistakes?

### Additional information

The html page is displayed as below as I click 'Mode chronologique':
![image](https://github.com/graphlab-fr/cosma/assets/61202052/45c76fce-212e-42ec-a9b8-51cd9030dae8)

**Comment by infologie** [comment]
Thanks @uuanqin for reporting this bug! I was able to reproduce it with a test folder. I'm notifying @Myllaume and we're going to look into it.

**Comment by infologie** [comment]
Hi @uuanqin. We have streamlined chronological mode for now. The parameter `chronological_record_meta` has been removed and chronological mode now automatically uses `begin` and `end` metadata. This closes the issue without really solving it. However, we will add the ability to define custom chronological metadata again in a future update. If you want, I'll notify you here when we do that.
