### ISSUE TITLE
[Bug] Dead Link on Demo Site

### ISSUE THREAD

**Issue by spiderweak** [graphlab-fr/cosma#7]
Not really a bug on the software.

Accessing the "Aide" link at the bottom of the https://cosma.graphlab.fr/demo.html opens a column with the link "Cliquez ici pour accéder à la documentation de Cosma" that points to https://hyperotlet.github.io/cosma/fr.html#utilisation-du-cosmoscope which, I suppose, is an old link for the project and would need to be modified to point to the actual documentation in the new project.

**Comment by infologie** [comment]
Good catch, thank you. I mirrored the docs at https://hyperotlet.github.io/cosma/fr.html as a quick fix and I modified the cosmoscope template so that future releases of Cosma use the proper link.
